name: playground
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <3.8.0"

dependencies:
  jaspr: ^0.18.2
  jaspr_router: ^0.6.4

dev_dependencies:
  build_runner: ^2.4.15
  jaspr_web_compilers: ^4.1.1
  jaspr_builder: ^0.18.2
  jaspr_lints: ^0.3.1
  jaspr_cli: ^0.18.2
  lints: ^5.1.1

jaspr:
  mode: server

