name: localization
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  jaspr: ^0.18.2
  jaspr_router: ^0.6.4
  slang: ^4.7.1

dev_dependencies:
  build_runner: ^2.4.15
  jaspr_web_compilers: ^4.1.1
  jaspr_builder: ^0.18.2
  jaspr_lints: ^0.3.1
  jaspr_cli: ^0.18.2
  lints: ^5.1.1

  slang_build_runner: ^4.7.0

